### ISSUE TITLE
What if I delete rounds and just run Compute one time?

### ISSUE THREAD

**Issue by DanqingZ** [jshun/ligra#11]
I noticed "long rounds = P.getOptionLongValue("-rounds",3);" in ligra.h file. And I am finding the same result is calculated four times, which seems taking more time. 

I reduced rounds to 1, does that mean actually setting rounds to 1 will take even longer time in terms of parallel computing? I do not understand why we need to compute the same thing for four times.

Also , if I deleted the for loops, and replace it with below code
```
graph<compressedSymmetricVertex> G =
readCompressedGraph<compressedSymmetricVertex>(iFile,symmetric); //symmetric graph
Compute(G,P);
G.del();
```
And I got the result:
```
size = 13233762
n = 7164775534703567937 m = 3677866877581936505 totalSpace = 3904913592795935540
reading file...
Segmentation fault: 11
```
I am thinking maybe it is because my input data file is too large, and some memory problem occur. But I am still confused, what is the best strategy here. I am running local graph clustering to get PPR vector for each node of a graph of 343299 nodes. So I also want to make sure that I choose an approach that saves time. Thanks!

**Comment by jshun** [comment]
By default, the code is run once to warm the cache and then 3 times to get 3 timings. If you don't need the timings you can pass the flag "-rounds 0", and it will run the code once without giving any timings.

I'm not sure why you got the seg fault after changing the code. The code you added is for reading a compressed graph. Perhaps you passed an input that hasn't been compressed.

**Comment by DanqingZ** [comment]
Oh thanks! I checked my code later and found out that there is some other issues that caused the problem.
