### ISSUE TITLE
BFS, Components and Pagerank fail for large compressed weighted graphs.

### ISSUE THREAD

**Issue by jayavanth** [jshun/ligra#17]
I have a bunch of weighted/unweighted graphs in `.adj` format and I'm trying to run BFS, CC and Pagerank on them. Since, BFS doesn't directly run weighted graphs, I used the `./encode` to compress the graphs and then run BFS on it. I'm getting segmentation faults when I run it with compressed weighted graphs, but they run fine when I run with compressed/uncompressed unweighted graphs.

To reproduce:
1. Download CTU-46.adj from here: [CTU-46](https://drive.google.com/file/d/1CEFq9Rrkqr-yGc5eG-kC5I3_AOF4FbLD/view?usp=sharing) and download CTu-uw-46.adj from here: [CTu-uw-46](https://drive.google.com/file/d/1lW169B7H4eFl-vPzFbtZ_88BN4yZ9qqP/view?usp=sharing)

2. Compress the matrix:
```
./encoder -w CTU-46.adj out46-w.compressed
./encoder CTu-uw-46.adj out46.compressed
```

3. Run BFS/Pagerank/Components

Weighted
```
./BFS -c out46-w.compressed          
size = 1396572
n = 41474 m = 85951 totalSpace = 369766
reading file...
inTotalSpace = 363182
creating graph...
[1]    15186 segmentation fault  ./BFS -c out46-w.compressed
```
Unweighted
```
./BFS -c out46-uw.compressed 
size = 994259
n = 41474 m = 85951 totalSpace = 164219
reading file...
inTotalSpace = 166416
creating graph...
Running time : 0.00235
Running time : 0.00234
Running time : 0.00164
```

**Comment by jshun** [comment]
Hi,

BFS, PageRank and CC only work for unweighted graphs. If you want to compute shortest paths on weighted graphs you can run the BellmanFord program.
