### ISSUE TITLE
Are the implementations in `apps/` multicore?

### ISSUE THREAD

**Issue by jayavanth** [jshun/ligra#18]
I tried to run a couple of them (BFS, CC, PR etc.) on large graphs and I see only one core at 100% with htop. Are those implementations in `apps/` multicore? If so, how do I make it run on multiple cores?

**Comment by ldhulipala** [comment]
Yes, but you have to compile the codes with one of the parallel flags enabled, otherwise the codes will treat all of the parallel for loops as sequential fors. For example, to compile with CILK you can set "export CILK=1" in your shell and then run the makefile.
