### ISSUE TITLE
-s flag issue

### ISSUE THREAD

**Issue by souravpati** [jshun/ligra#22]
I downloaded the snap file soc-LiveJournal1
Converted it using SNAPtoAdj in /utils
```
$ ./SNAPtoAdj soc-LiveJournal1.txt lig_socLJ1
```
Then I tried to Run BFS on this data in the /apps folder
This was the output
```
$ ./BFS lig_socLJ1
Segmentation fault(core dumped)
```
However, when I used the -s flag
```
$ ./BFS -s lig_socLJ1
Running time : 0.571
Running time : 0.518
Running time : 0.511
```
As you can see, I did not use the SNAPtoAdj utility with the -s flag.
I was wondering, where I could be wrong. Please, help me out.

**Comment by ldhulipala** [comment]
Hi Sourav,

I tried the same steps as you, but get the following:
```
wget https://snap.stanford.edu/data/soc-LiveJournal1.txt.gz
gzip -d soc-LiveJournal1.txt.gz
./BFS lig_socLJ1
Running time : 0.0172
Running time : 0.0179
Running time : 0.0169
```
I tried this with and without the CILK flag set (CILK=1). Could you try recompiling, and maybe let us know the compiler you're using/the command line flags you used when compiling BFS?

**Comment by souravpati** [comment]
I used openmp

**Comment by ldhulipala** [comment]
Thanks for letting us know. It seems that adding -march=native when compiling with -O3 fixes the problem (at least on my machine). Can you try adding the flag to the makefile and let me know if it fixes it for you?

**Comment by souravpati** [comment]
Thank you. It works!

**Comment by ldhulipala** [comment]
Great, I'll commit a fix to the makefile. Thanks for letting us know!
