### ISSUE TITLE
SNAPtoAdj segmentation fault

### ISSUE THREAD

**Issue by baby-panda** [jshun/ligra#25]
I compiled SNAPtoAdj with Cilk enabled, and the tool works well for all my graphs, except for [friendster](https://snap.stanford.edu/data/com-Friendster.html).
It ends up with segmentation fault, if I tell the tool to convert the friendster graph into a symmetric one.
The command is like
~~~bash
./SNAPtoAdj -s friendster.txt friendster_J
~~~
wghSNAPtoAdj has similar issue as well.  
  
I tried different compilers, icpc and g++ 5.4.0.
When compiling, it prints out the following commands respectively.
~~~bash
icpc -std=c++14 -O3 -DCILKP   -o SNAPtoAdj SNAPtoAdj.C
~~~
or
~~~bash
g++ -std=c++14 -fcilkplus -lcilkrts -O2 -DCILK   -o SNAPtoAdj SNAPtoAdj.C
~~~
However, the executable files of both failed on friendster.  
  
Could someone give me any idea what is going wrong?
Thanks in advance!

**Comment by jshun** [comment]
Please try to compile with the environment variable LONG defined, e.g.,
`LONG=1 g++ -std=c++14 -fcilkplus -lcilkrts -O2 -DCILK   -o SNAPtoAdj SNAPtoAdj.C
`
