### ISSUE TITLE
Segfault using SNAPtoAdj on Twitter graph

### ISSUE THREAD

**Issue by vaastav** [jshun/ligra#33]
I am trying to convert the Twitter graph to the adjacency list format but it always seems to end in a segfault.

I tried debugging with gdb and it seems to be happening in theutils/graphIO.hpp file when the words are being converted into edges.

Any help would be greatly appreciated.

**Comment by vaastav** [comment]
This is the output I get when I try to debug using gdb

Program received signal SIGSEGV, Segmentation fault.
0x00000000004035e7 in _seq<long> sequence::pack<long, long, identityF<long> >(long*, bool*, long, long, identityF<long>) ()
(gdb) bt
#0  0x00000000004035e7 in _seq<long> sequence::pack<long, long, identityF<long> >(long*, bool*, long, long, identityF<long>) ()
#1  0x0000000000402863 in benchIO::stringToWords(char*, long) ()
#2  0x0000000000403e5a in edgeArray<unsigned int> benchIO::readSNAP<unsigned int>(char*) ()
#3  0x0000000000401cd3 in main ()

**Comment by jshun** [comment]
It's possible that you need to use a machine with more RAM.
