### ISSUE TITLE
Error when make -j 

### ISSUE THREAD

**Issue by OneoneWang** [jshun/ligra#35]
[clong@shamrock apps]$ make -j
g++ -std=c++14 -O3   -DBYTERLE   -o encoder encoder.C
g++ -std=c++14 -O3   -DBYTERLE   -o decoder decoder.C
g++ -std=c++14 -O3   -DBYTERLE   -o BFS BFS.C
g++ -std=c++14 -O3   -DBYTERLE   -o BC BC.C
g++ -std=c++14 -O3   -DBYTERLE   -o BellmanFord BellmanFord.C
g++ -std=c++14 -O3   -DBYTERLE   -o Components Components.C
g++: error: unrecognized command line option ‘-std=c++14’
g++: error: unrecognized command line option ‘-std=c++14’
make: *** [encoder] Error 1
make: *** Waiting for unfinished jobs....
make: *** [decoder] Error 1
g++: error: unrecognized command line option ‘-std=c++14’
make: *** [BFS] Error 1
g++: error: unrecognized command line option ‘-std=c++14’
make: *** [BC] Error 1
g++: error: unrecognized command line option ‘-std=c++14’
make: *** [BellmanFord] Error 1
g++: error: unrecognized command line option ‘-std=c++14’
make: *** [Components] Error 1

**Comment by lushl9301** [comment]
Hi, what is your gcc version?

**Comment by jshun** [comment]
You probably have to use a newer version of gcc. We have tested on gcc >= 5.3.0.
