### ISSUE TITLE
Question on CC (connected components)

### ISSUE THREAD

**Issue by Huyuwei** [jshun/ligra#40]
Below is the edgeMap function in https://github.com/jshun/ligra/blob/master/apps/Components.C

```
inline bool update(uintE s, uintE d){ //Update function writes min ID
  uintE origID = IDs[d];
  if(IDs[s] < origID) {
    IDs[d] = min(origID,IDs[s]);
    if(origID == prevIDs[d]) return 1;
  }
  return 0;
}
```

Why do we need `if(origID == prevIDs[d])`? Is this check always true?

**Comment by jshun** [comment]
This will return true exactly once per iteration for an updated vertex. The check is to avoid duplicates from being returned in the output of edgeMap.
