### ISSUE TITLE
How to set the threads numbers of Ligra?

### ISSUE THREAD

**Issue by libaoke** [jshun/ligra#42]
How to set the threads numbers of Ligra?

**Comment by lushl9301** [comment]
you may refer to 
https://github.com/jshun/ligra/blob/d4c7dd34fcdb9510ab6adb1dc19793a38888c9ee/apps/localAlg/Nibble-Parallel.C#L83-L84


use the function setworkers()

https://github.com/jshun/ligra/blob/d4c7dd34fcdb9510ab6adb1dc19793a38888c9ee/ligra/parallel.h#L84

**Comment by libaoke** [comment]
Is that so?

when make:
make -j  OPENMP=1
when run: 
./BFS -s -p 2 ../inputs/rMatGraph_J_5_100

**Comment by libaoke** [comment]
> you may refer to
> 
> https://github.com/jshun/ligra/blob/d4c7dd34fcdb9510ab6adb1dc19793a38888c9ee/apps/localAlg/Nibble-Parallel.C#L83-L84
> 
> use the function setworkers()
> 
> https://github.com/jshun/ligra/blob/d4c7dd34fcdb9510ab6adb1dc19793a38888c9ee/ligra/parallel.h#L84

Thank you very much.
Is that so?
when make:
make -j  OPENMP=1
when run: 
./BFS -s -p 2 ../inputs/rMatGraph_J_5_100

But the runtimes don't change when -p 2 or -p 4.

**Comment by lushl9301** [comment]
@libaoke 
the implementation of BFS does not take -p as an option. you may add these two lines on your own
https://github.com/jshun/ligra/blob/d4c7dd34fcdb9510ab6adb1dc19793a38888c9ee/apps/localAlg/Nibble-Parallel.C#L83-L84

**Comment by libaoke** [comment]
> @libaoke the implementation of BFS does not take -p as an option. you may add these two lines on your own
> 
> https://github.com/jshun/ligra/blob/d4c7dd34fcdb9510ab6adb1dc19793a38888c9ee/apps/localAlg/Nibble-Parallel.C#L83-L84

Thank you @lushl9301

**Comment by libaoke** [comment]
> @libaoke the implementation of BFS does not take -p as an option. you may add these two lines on your own
> 
> https://github.com/jshun/ligra/blob/d4c7dd34fcdb9510ab6adb1dc19793a38888c9ee/apps/localAlg/Nibble-Parallel.C#L83-L84
 @lushl9301 Could Ligra specify the size of memory space？ such as 16GB DRAM or 32GB DRAM.

**Comment by lushl9301** [comment]
I don't think so.
but you can try this https://www.baeldung.com/linux/limit-resource-consumption

or use a docker

**Comment by libaoke** [comment]
> I don't think so. but you can try this https://www.baeldung.com/linux/limit-resource-consumption
> 
> or use a docker


Thanks. I have another question:
Does BFS cannot traverse all vertices？


while(!Frontier.isEmpty()){ //loop until frontier is empty
vertexSubset output = edgeMap(GA, Frontier, BFS_F(Parents));
Frontier.del();
Frontier = output; //set new frontier
}

**Comment by lushl9301** [comment]
that is a graph-specific question.

if the graph is undirected and it only has one connected component. you will visit all vertices.
otherwise, may not.

**Comment by libaoke** [comment]
OK.  Thanks again.
