### ISSUE TITLE
[edgeMap] segfault in sparse mode when graph has less than 20 edges

### ISSUE THREAD

**Issue by jmftrindade** [jshun/ligra#46]
This is on master branch. Steps to replicate:

1. Change `BellmanFord.C` to use `no_dense` instead of `dense_forward`, but don't change the initial threshold of `G.m/20` here:

https://github.com/jshun/ligra/blob/7755d95fbac4a587ee7c5920d1b927c545f97d07/apps/BellmanFord.C#L79

2. Use a small graph with less than 20 edges as input, get segfault.

Why:
Step 1 passes a threshold of 0 to `edgeMap`. This is not a problem when in dense mode, but when in sparse mode, it leads to activating a code path that skips computation of out degrees here:

https://github.com/jshun/ligra/blob/7755d95fbac4a587ee7c5920d1b927c545f97d07/ligra/ligra.h#L248

Later edgeMap tries to deference a nullptr by attempting to run a prefix-sum on the `offsets` array, which is pointing to  `degrees` (now null because of above):

https://github.com/jshun/ligra/blob/7755d95fbac4a587ee7c5920d1b927c545f97d07/ligra/ligra.h#L119

In the example above, `threshold` was set to 0 by the application. However, edgeMap can also end up setting it 0 here:

https://github.com/jshun/ligra/blob/7755d95fbac4a587ee7c5920d1b927c545f97d07/ligra/ligra.h#L238

(A threshold of 0 again is not a problem when in dense mode, but skips degrees computation when in sparse mode)

A potential fix on `edgeMap` (instead of on the application) would be to do this, which is what I do locally (UPDATE: changed it so that we don't accidentally overwrite user-specified threshold):
```
  if (threshold == -1) {
    if (numEdges > 20) {
      threshold = numEdges / 20;  // default threshold
    } else {
      // num edges is too small, use 1 as a threshold instead
      threshold = 1;
    }
  } 
```

Julian, let me know if you're ok with this and I'll send it over.

**Comment by jshun** [comment]
Thanks. I fixed it another way since setting a threshold of 0 is a way to indicate that we want only dense iterations.
