### ISSUE TITLE
RandLocalGraph seg faults when n > m 

### ISSUE THREAD

**Issue by paraggupta1993** [jshun/ligra#8]
How to produce : 
```
$./utils/randLocalGraph -s -m 100 -n 101 graph_file.txt
Segmentation fault (core dumped)
```
Does randLocalGraph not permit to generate graph where  n > m ? (it works for n <= m)  

( I am trying to generate graph with many components, any help on that will be great)
Thanks !

**Comment by jshun** [comment]
Thanks for pointing out the error. The code has been fixed so it now works with n > m.

Julian

**Comment by paraggupta1993** [comment]
Thanks for this awesome library !
