### ISSUE TITLE
Could sweep cut result be returned?

### ISSUE THREAD

**Issue by DanqingZ** [jshun/ligra#9]
could I also get all the members of returned set S? I want to know what are the index of nodes that belong to the local community of the certain input node. Many thanks!

**Comment by DanqingZ** [comment]
I checked the sweep.h header file and it seems only below are returned as a sweepObject:
return sweepObject(bestConductance,bestCut+1,bestVol,totalDegree/2,bestEdgesCrossing);

**Comment by jshun** [comment]
I've added some code to print out the set in sweep.h. To enable printing, you have to uncomment the line #define PRINT_SET in sweep.h.

**Comment by DanqingZ** [comment]
works for me! Thanks!
